### PR TITLE
fix: retry initialization

### LINKED ISSUE #57: Uncaught Error: This API only accepts integers
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 8.1.6

### Stack Trace

Uncaught Error: This API only accepts integers

```
At /Users/kvad/.atom/packages/x-terminal/node_modules/xterm/lib/xterm.js:1

Error: This API only accepts integers
    at /packages/x-terminal/node_modules/xterm/lib/xterm.js:1:55468
    at Array.forEach (<anonymous>)
    at e._verifyIntegers (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:55412)
    at e.resize (/packages/x-terminal/node_modules/xterm/lib/xterm.js:1:52749)
    at e.fit (/packages/x-terminal/node_modules/xterm-addon-fit/lib/xterm-addon-fit.js:1:1704)
    at HTMLElement.refitTerminal (/packages/x-terminal/src/element.js:692:18)
    at HTMLElement.applyPendingTerminalProfileOptions (/packages/x-terminal/src/element.js:679:9)
    at IntersectionObserver.terminalDivIntersectionObserver.IntersectionObserver.root (/packages/x-terminal/src/element.js:107:10)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-js-import 1.4.0 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
react-autocomplete 1.2.0 
terminal-plus 0.14.5 
x-terminal 8.1.6 
```

### PR DESCRIPTION
**Pull request by aminya**
A simple fix for #57. Whenever this error happens, I try again and it works the second time. So I think it is better to implement the retry in the code!

Fixes #57

### CODE REVIEW

**Comment by UziTech** [comment]
It is this line that is failing according to the stack traces in #57:

https://github.com/bus-stop/x-terminal/blob/d91c0a416b76666e9d0654cf75d7ec73a66dbf10/src/element.js#L672

we could just add a try catch and fail silently but it would be better to figure out why it is failing.

**Comment by UziTech** [comment]
#136 might fix #57 it prevents `.fit()` from being called when the terminal width or height is 0

**Comment by aminya** [comment]
I will try that!

**Comment by aminya** [comment]
I will close this in favor of #136

**Pull request closed without merging**
