### PR TITLE
fix: fix terminal resize when hidden

### LINKED ISSUE #135: Terminal output cleared with multiple tabs [BR]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [x] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description

When opening multiple tabs in the same position (i.e. right dock), output of all other tabs will be cleared automatically

### Steps to reproduce

1. Open terminal in the right dock
2. Type in any command to get some output on the screen
3. Open another terminal tab in the right dock
4. Output from the first terminal is cleared

**Expected behavior:**

Output from all non-active tabs should remain unaffected when a new terminal is opened in the same location
Output from tab should not be affected when unfocused.

**Actual behavior:**

The output is cleared when a new tab is opened in the same location or when a tab is unfocused (demonstrated by the following 2 videos)
https://www.youtube.com/watch?v=Wpq_OmmHr4w
https://www.youtube.com/watch?v=3KLlx4Vk5JQ

**Reproduces how often:**

Always

### Versions

```
> atom --version
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 3.7.1
git 2.25.0
visual studio 2015
```
OS name and version: **Windows 10 x64**
Terminal version: **9.0.3**

### PR DESCRIPTION
**Pull request by UziTech**
fixes #135

### CODE REVIEW

**Comment by UziTech** [comment]
This might also fix #57

**Comment by aminya** [comment]
I am testing this. I will see if that error happens again!

**Comment by aminya** [comment]
I again got the error:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [x-terminal](https://github.com/bus-stop/x-terminal) package 9.0.3


### Stack Trace

Uncaught Error: This API only accepts integers

```
At C:\Users\yahyaaba\Documents\GitHub\JavaScript\x-terminal\node_modules\xterm\lib\xterm.js:1

Error: This API only accepts integers
    at e._verifyIntegers (~/Documents/GitHub/JavaScript/x-terminal/node_modules/xterm/lib/xterm.js:1:101386)
    at e.resize (~/Documents/GitHub/JavaScript/x-terminal/node_modules/xterm/lib/xterm.js:1:98497)
    at e.fit (~/Documents/GitHub/JavaScript/x-terminal/node_modules/xterm-addon-fit/lib/xterm-addon-fit.js:1:1723)
    at HTMLElement.refitTerminal (~/Documents/GitHub/JavaScript/x-terminal/src/element.js:688:18)
    at HTMLElement.applyPendingTerminalProfileOptions (~/Documents/GitHub/JavaScript/x-terminal/src/element.js:670:9)
    at IntersectionObserver.terminalDivIntersectionObserver.IntersectionObserver.root (~/Documents/GitHub/JavaScript/x-terminal/src/element.js:109:11)
```

### Commands

```
     -0:42.7.0 core:paste (input.hidden-input)
     -0:42.2.0 core:save (input.hidden-input)
     -0:34.1.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
  6x -0:28.4.0 core:delete (input.hidden-input)
     -0:26.1.0 core:save (input.hidden-input)
     -0:22.3.0 core:backspace (input.hidden-input)
     -0:21.8.0 core:save (input.hidden-input)
     -0:21.2.0 core:backspace (input.hidden-input)
     -0:21 core:save (input.hidden-input)
     -0:19.5.0 core:backspace (input.hidden-input)
     -0:19.2.0 core:save (input.hidden-input)
  3x -0:17.3.0 core:backspace (input.hidden-input)
     -0:16.6.0 core:save (input.hidden-input)
     -0:12.8.0 command-palette:toggle (input.hidden-input)
     -0:11.9.0 core:confirm (input.hidden-input)
     -0:11.9.0 x-terminal:open (input.hidden-input)
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-alignment 0.13.0 
atom-bash 1.1.1 
atom-beautify 0.33.4 
atom-commander 0.12.0 
atom-console 0.4.6 
atom-ide-base 1.1.1 
atom-ide-datatip 0.13.2 
atom-ide-definitions 0.3.6 
atom-ide-hyperclick 1.0.3 
atom-ide-javascript 1.2.1 
atom-ide-julia 0.1.0 
atom-ide-markdown-service 1.3.1 
atom-ide-outline 1.9.4 
atom-ide-signature-help 0.8.0 
atom-ide-template-rust 0.1.0 
atom-ide-ui 0.13.0 
indent-detective 0.4.0 
atom-material-ui 2.1.3 
atom-matlab-editor 0.4.0 
atom-minify 0.8.0 
atom-reverser 3.0.4 
atom-terminal 0.8.0 
atom-typescript 13.9.2 
atomic-management 0.3.1 
atomizr 0.23.2 
auto-fold 0.4.0 
autocomplete 0.47.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-clang 0.13.1 
autocomplete-en-en 0.2.0 
autocomplete-paths 2.12.2 
build 0.70.0 
build-npm-apm 0.12.0 
busy-signal 2.0.1 
clean-context-menu 0.3.2 
colorful-json 1.1.0 
cson-parser 0.1.0 
ctags-status 1.4.0 
file-icons 2.1.42 
find-trailing-whitespace 0.1.0 
fold-functions 0.11.0 
fold-lines 0.2.2 
font-viewer 0.4.0 
glow undefined 
hello_world-webpack 0.1.0 
hey-pane undefined 
highlight-selected 0.17.0 
Hydrogen 2.14.4 
hyperclick 0.1.5 
ide-bash 1.0.11 
ide-c-cpp 0.1.0 
ide-clangd 0.4.0 
ide-css 0.3.4 
ide-json 0.2.1 
ide-powershell 0.1.0 
ide-python 1.5.0 
ide-typescript 0.9.1 
ide-yaml 0.7.0 
ide-yml 0.7.8-0 
intentions 1.1.5 
javascript-drag-import 0.1.13 
javascript-refactor 0.7.1 
json-converter 0.2.4 
juno-plus 0.12.2 
keyword-pair-matcher 0.2.1 
kite 0.185.0 
language-autohotkey2 1.0.1 
language-cmake 1.2.0 
language-github-actions 0.1.0 
language-julia 0.19.3 
language-latex 1.2.0 
language-matlab 0.2.1 
language-matlab-octave 1.0.5 
language-matlab-plus 1.12.0 
language-pfm 0.82.0 
language-powershell 5.0.0 
language-reg 0.0.0 
latex-autocomplete 1.1.1 
latex-completions 0.3.6 
latex-friend 0.0.11 
latex-image-paste 0.5.0 
latex-itemizer 1.1.1 
latex-tree 0.5.0 
latex-wordcount 0.6.0 
less-than-slash 0.19.0 
linter 2.3.1 
linter-clang 4.1.2 
linter-cpplint 2.1.0 
linter-eslint 8.5.5 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-julia 0.8.3 
linter-matlab 1.3.0 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-spell-latex 0.11.0 
linter-tslint 1.10.43 
linter-ui-default 1.8.1 
markdown-preview-plus 4.5.0 
markdown-preview-plus-opener 0.4.0 
markdown-writer 2.11.10 
menu-manager 0.6.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-lens 0.7.0 
minimap-linter 2.2.1 
minimap-plus 4.32.0 
minimap-titles 1.15.0 
multi-copy 0.1.0 
multi-cursor-plus 1.2.0 
multi-line-editor 1.6.0 
multi-paste2 0.4.1 
package-ts-generator 0.1.2 
pdf-view 0.72.0 
preview 0.19.0 
preview-inline 1.5.1 
project-manager 3.3.8 
Quick-JavaScript 2.2.0 
script 3.26.0 
snippet-generator-plus 0.1.2 
snippets-plus 0.10.2 
split-diff 1.6.1 
string-encoder 0.2.0 
Sublime-Style-Column-Selection 1.7.5 
symbols-tree-nav 0.15.5 
sync-settings 4.3.8 
teletype 0.13.4 
tool-bar 1.3.0 
trailing-spaces 0.4.0 
tree-view-git-status 1.5.3 
turbo-javascript 1.4.0 
uber-juno 0.3.0 
vim-mode-plus 1.36.4 
web-view 3.0.0 
x-terminal 9.0.3 
```

**Comment by UziTech** [comment]
@aminya what were you doing with x-terminal when you got the error?

**Comment by aminya** [comment]
> @aminya what were you doing with x-terminal when you got the error?

I just ran `x-terminal open`. This error happens only when you try to open a terminal! I use the bottom dock for my terminal's position.

**Comment by UziTech** [comment]
I was able to recreate it. It seems that if xterm is initialized with a hidden div than it gives itself a 0px height and fails to resize. I'm thinking this is a bug in xterm but I'm not exactly sure where it is.

I managed to fix it by only initializing xterm after the div is visible.

It was only happening in the bottom dock when the dock was closed and the Linter panel is in the bottom dock. For some reason Linter makes itself visible when the dock opens making the newly added item (x-terminal) not visible which makes xterm give itself a 0px height and fail when it tries to resize.

**Comment by aminya** [comment]
> I was able to recreate it. It seems that if xterm is initialized with a hidden div than it gives itself a 0px height and fails to restart. I'm thinking this is a bug in xterm but I'm not exactly sure where it is.
> 
> I managed to fix it by only initializing xterm after the div is visible.
> 

Great! That's awesome that you found the reason.

> It was only happening in the bottom dock when the dock was closed and the Linter panel is in the bottom dock. For some reason Linter makes itself visible when the dock opens making the newly added item (x-terminal) not visible which makes xterm give itself a 0px height and fail when it tries to resize.

This is really annoying. Can we make a PR to linter UI to fix this? I tend to open and close the terminal a lot, but this linter enforcing focus is annoying.

**Comment by UziTech** [comment]
> This is really annoying. Can we make a PR to linter UI to fix this? I tend to open and close the terminal a lot, but this linter enforcing focus is annoying.

I created an issue on the linter-ui-default repo: https://github.com/steelbrain/linter-ui-default/issues/582

**Comment by Abhi2019** [comment]
I am getting the same issue when doing resizing the terminal.

 <ResizeObserver
            onResize={(rect) => {
              fitAddon.fit();
              console.log("Resized. New bounds:", rect.width, "x", rect.height);
            }}
            onPosition={(rect) => {
              console.log("Moved. New position:", rect.left, "x", rect.top);
            }}
          />

It was providing NaN value to the resize function, could someone look into this.

**Comment by UziTech** [comment]
@Abhi2019 Can you create a new issue and fill out the template so we can track your error?

**Pull request merged**
