### PR TITLE
Rollup

### PR DESCRIPTION
**Pull request by aminya**
This speeds up the actual loading of the package by 4.2 times (~230 -> 55) by building it using rollup.

Benchmark with activation hook disabled:
After:
image

Before
image

Note: the spec runs on the src instead of the bundle. If you prefer to test the bundle instead (let me know), in the spec, you should import everything from the `dist/x-terminal.js`, ~~which means they should be exported by `src/x-terminal.js`. Another alternative is to create a bundle for the tests as well.~~

Edit: regarding the tests, there is a better way for bundling with exports from each individual file:
https://github.com/rollup/plugins/tree/master/packages/multi-entry

Edit2: we should not wait for the multi-entry feature. They have an issue https://github.com/rollup/plugins/issues/488 which needs to be fixed before I can add that to this PR.

### CODE REVIEW

**Comment by UziTech** [comment]
Seems like a lot of extra code to maintain for ~150ms

**Comment by aminya** [comment]
No maintenance is needed, I just copied it from [atom-ide-template-js](https://github.com/atom-ide-community/atom-ide-template-js). This code will never change. If you like I can pin the versions, so the versions don't change at all.  

 By the way, 150ms is a lot! It is half of the whole atom load time. The point of all of my recent efforts is to enhance the experience of the end-users for the price of copy-pasting a couple of more lines.

**Comment by aminya** [comment]
I removed unused plugins to make this more compact. I rarely change my configurations for different projects. I just copy-paste my template everywhere. However, I did it based on your request.

**Comment by UziTech** [comment]
pinning versions will just create insecure legacy code.

It would be great if it only took ~450ms for Atom to start up. Mine is closer to 3000ms and it looks like x-terminal only takes 42ms to load. I'm still not sure the extra work is worth a few milliseconds.

image

**Comment by aminya** [comment]
@UziTech If you invite me to this organization, I can maintain the code (bumping deps) personally. 



> pinning versions will just create insecure legacy code.
> 
> It would be great if it only took ~450ms for Atom to start up. Mine is closer to 3000ms and it looks like x-terminal only takes 42ms to load. I'm still not sure the extra work is worth a few milliseconds.
> 
> image

You should disable the activation hook for the measurements, and look into the load time in the settings. Sometimes timecope does not show the correct loading time. Your timings seem very strange. Probably this is because of CPU, drive, OS differences, or there might be a problem with your setup

**Comment by UziTech** [comment]
> You should disable the activation hook for the measurements

If you disable the activation hooks then it will not give you the correct startup time. If it only improves the performance in theory and not in practice than this definitely sounds like premature optimization.

**Comment by aminya** [comment]
We want to optimize the performance of our actual code not how Atom defers it. To be even more exact, you should measure the execution time like this:

```js
let t1 = window.performance.now()
// code
console.log(window.performance.now()-t1)
```

For example, for activation time:
```js
export function activation() {
	let t1 = window.performance.now()
	// activation code
	console.log(window.performance.now()-t1)
}
```

 If I enable the activation hook, the loading time becomes 5ms for me (just parsing package.json). It means atom correctly defers it, but this does not mean Atom does not get laggy during the initial times (after loading core-shell).

**Comment by the-j0k3r** [comment]
> This speeds up the actual loading of the package by 3 times (~200 -> 65) by building it using rollup.

IDK why your startup times are high in both cases, My dev setup is on a VM with Windows 10 with a virtualdisk stored on regular HDD (WD Green). 

Im also using non community build of Atom 1.48.0, my x-terminal startup time overhead is much, but much much lower (and without this addition)

generic

Capture

Edit: The highest I have ever had was below 30ms, I can start Atom 10 times and never exceeds 30ms

Just did 5 runs all at 4ms. Its so low that I question the need for this.

**Comment by aminya** [comment]
@the-j0k3r remove the activation hook settings from package.json to see the actual load time. Not doing that you only see the time it takes for Atom to parse the package.json. No JavaScript runs if you don't do that.

**Comment by aminya** [comment]
@UziTech I created two packages to wrap the rollup plugins (`rollup-plugin-atomic`) and babel presets (`babel-preset-atomic`). Now the code is much more compact, and you do not need to maintain anything.

**Comment by UziTech** [comment]
> you do not need to maintain anything.

Just because the dependencies are abstracted doesn't mean we won't need to debug them if something goes wrong. And if `rollup-plugin-atomic` ever becomes unmaintained then we will need to do more work to work around it.

I just don't see the benefit of adding any dependencies let alone extra developer time building in order to test things for a few milliseconds of speed that most users won't notice. If that 200ms was somehow losing us money I could justify it but I see no pros and a few small cons to adding a build step.

**Comment by aminya** [comment]
If you do not like maintaining this, please invite me so I can help you with that.

I am using these packages everywhere, I will not stop maintaining them. I created one package so I can just maintain that instead of copy-pasting things around. 

Regarding the time, `200ms` on my system is quite a lot. It is almost 1/3 of Atom's loading on my system.

Anyways, if you still do not want to merge this PR or make a member, I will make a synchronized fork of x-terminal in atom-ide-community so we can integrate it into atom.

**Comment by UziTech** [comment]
> I will make a synchronized fork of x-terminal in atom-ide-community so we can integrate it into atom.

This seems like the best option.

**Comment by aminya** [comment]
For the record: providing multi-entry bundle (which creates a bundle with all the exports from single files) on Windows is blocked by https://github.com/rollup/plugins/pull/506. I will wait until Rollup merges that or make Windows working like Linux.

**Comment by frank-dspeed** [comment]
@aminya you did not understand it the error is not windows related the error is that you have no option to define the filename.

the one in the plugin was designed to never get writen to disk :)

**Comment by aminya** [comment]
@frank-dspeed Not having an option for defining the output name is bigger, but the fact that Windows does not support the normal Colons is blocking this. I could get along with the default name and rename it manually afterward. In the long run, I would vote for adding the option for sure.

Anyways, I will wait until the issue is closed somehow. 😄

**Comment by frank-dspeed** [comment]
```js
import { promise as matched } from 'matched';

export default function multiEntry(conf={}) {
   const config = { 
    include: [],
    exclude: [],
    exports: true,
    outputFile: 'multi-entry',
    ...conf
  }
  let { outputFile, include, exclude, exports } = config;
  if (include.length === 0) {
      // We need any includes
      throw new Error('We need Include and a outputFile')
  }
  if (typeof include === 'string' || typeof include === 'array'){
      new Error('type of include needs to be string or array of strins')
  }
  
  if (typeof exclude === 'string' || typeof exclude === 'array'){
    new Error('type of exclude needs to be string or array of strins')
  }

  //String option to array
  if (typeof exclude === 'string') {
    exclude = [exclude]
  }   
  if (typeof include === 'string') {
    include = [exclude]
  }   

  let prefix = exports ? 'export * from' : 'import'
  let exporter = (path) => `${prefix} ${JSON.stringify(path)};`;

  return {
    buildStart() {
       this.emitFile({ type: 'chunk', id: outputFile })
    },
    resolveId(id) {
      return id === outputFile ? id : null;
    },
    load(id) {
      if (id === outputFile) {
        const patterns = include.concat(exclude.map((pattern) => `!${pattern}`));
        return matched(patterns, { realpath: true })
            .then(paths => paths.map(exporter).join('\n'));
      }
      return null
    }
  };
}
``` 

i have made a new version but it needs testing and all that expect it to take a week or a bit more as it is not high priority but maybe you want to copy paste it directly into your configuration


```js
import multiEntry from 'multi-entry'
export default {
  input: [],
  plugins: [multiEntry({
   include: ['any/path/befor/on/**/*.js'],
    exclude: [],
    exports: true,
    outputFile: 'multi-entry',
})]
}
```

This version does not use or rewrites the input options so you can set them to empty array if you do not want to bundle extra files all other files should be put into include and the outputFile name is the setable configuration

**Comment by aminya** [comment]
@frank-dspeed Thank you so much! I will test this.

**Comment by UziTech** [comment]
I'm going to close this as I don't think this will get merged

**Pull request closed without merging**
