### PR TITLE
[fix] Move from document.registerElement to window.customElements.define

### LINKED ISSUE #509: HTMLDocument.registerElement is deprecated.
Use `customElements.define` instead of `document.registerElement` see https://javascript.info/custom-elements
```
HTMLDocument.registerElement (file:///C:/ProgramData/wersw/atom/app-1.63.0/resources/app.asar/static/index.js:160:12)
Object.<anonymous> (C:\Users\wersw\.atom\packages\x-terminal\src\profile-menu-element.js:521:44)
Object.<anonymous> (C:\Users\wersw\.atom\packages\x-terminal\src\profile-menu-element.js:527:3)
Module._compile (<embedded>:11:149913)
Object..js (<embedded>:11:153507)
Module.load (internal/modules/cjs/loader.js:992:32)
```

### PR DESCRIPTION
**Pull request by Spiker985**
Should fix #509

All tests passed, and project was linted before commit.
image
image

### CODE REVIEW

**Comment by Spiker985** [comment]
@UziTech Would you mind looking at this? I would've pinged someone else, however, you did say that PRs were welcome 😅

**Comment by UziTech** [comment]
Looks like some tests are failing in ci. Once those are passing I can merge this.

**Comment by Spiker985** [comment]
I'll take a look, but my current assumption is because the original specs were using the `new <element>` syntax, and are now using a function which performs a similar action - that the specs are now incompatible

Even though those specs were updated alongside the methods

**Comment by Spiker985** [comment]
I'm actually going to rescind this PR for now

**Pull request closed without merging**
