### PR TITLE
feat: add context-menu items to tree view and tabs

### LINKED ISSUE #96: Why use the project directory when the cwd is in the project path?[Q]
For the initialize() in the model.js, why use the project directory when the cwd is in the project path?

### LINKED ISSUE #212: [FR] Open project folder in terminal
### Description
For example in the file manager Thunar there is a feature to open a selected folder in a new terminal window by the right mouse button context menu.
I think it would be great, if it's possible to implement this in Atom for the context menu of project folders.

### Possibly connected to:
- https://github.com/bus-stop/x-terminal/issues/38
- https://github.com/bus-stop/x-terminal/issues/96

### PR DESCRIPTION
**Pull request by UziTech**
Adds context menu items to tree-view and tab-bar. When executing from tree-view or tab bar opens terminal in folder of selected item.

This will be a breaking change with the way we determine cwd.

fixes #212 
fixes #96

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Cant say I agree with implementation design, but its better than nothing

**Comment by UziTech** [comment]
Ya that is one reason it is still a draft. I was trying to avoid this being a breaking but because of the way we get cwd it might have to be.

**Comment by UziTech** [comment]
The only other way I could think of doing this would be to have separate commands for the tree-view and tab-bar context menu but I didn't want to create a whole bunch of `x-terminal:open-split-up-context-menu` commands.

**Comment by the-j0k3r** [comment]
Terminus does this fairly well, maybe thats a starting point.

In all honesty, I cant see any such addition being a non breaking change your right and we agree on this much =)

**Comment by UziTech** [comment]
> Terminus does this fairly well, maybe thats a starting point.

It doesn't look like terminus does anything with the items selected in tree-view.

**Comment by the-j0k3r** [comment]
But it maps to folder just fine optionally  which is the point and does via treeview

Actually I posted a gif of it doing it... let me see if I can find it on here

Here https://github.com/bus-stop/x-terminal/issues/38#issuecomment-606550248 xterminal vs terminus

**Comment by UziTech** [comment]
The "map terminals" feature is different than just changing cwd based on context-menu element. For one the map terminals feature does not work when you want to have multiple terminals open or when you want a terminal to open to a specific folder and keep that terminal open even when changing files in Atom.

**Comment by vivi90** [comment]
@UziTech Sorry but it doesn't open the selected folder in the terminal for me. Don't see, what i am doing wrong.

**Pull request merged**
