### PR TITLE
chore(meta): readme changes

### PR DESCRIPTION
**Pull request by the-j0k3r**

### CODE REVIEW

**Comment by the-j0k3r** [comment]
WIP dont merge

**Comment by the-j0k3r** [comment]
I'll sort out the badges later as  per org

**Comment by the-j0k3r** [comment]
1) OK images wont show up in PR as this expects renamed images to be already in master branch and they are in readme branch until this is merged. In theory =)

<s>2) TODO: The readme could do with more trimming this info was prior to prebuilt binaries. 

It still has [instructions to build binaries via node-gyp](https://github.com/bus-stop/x-terminal/blob/bbc41ed94d32fd59db4a512277fefd94009d7916/README.md#one-time-prerequisites), this perhaps should be moved  to wiki or other place. This would be a rare instance having to rebuild binaries. In any case its incomplete.</s> Done in https://github.com/bus-stop/x-terminal/pull/11/commits/607825ae0ea4f5bd27f7d04a26d3be61659ea480

3) Need to add a contributing.md and more general cleanup. I could copy the contributing MD from terminus but that need work to use in this project as doesnt use standard js.

for now though this is good to go.

**Review by UziTech — APPROVED** [review]

**Comment by UziTech** [comment]
LGTM. I would be ok with using eslint-standard.

**Comment by the-j0k3r** [comment]
I think Ill give it a try to do new screenshots and gifs some of these can use a refresh.

**Comment by the-j0k3r** [comment]
OK kicking this in, the rest for another time

**Pull request merged**
